apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: "{{ .Values.service.clusterIP }}"
  selector:
    service: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.service.http }}
    targetPort: {{ .Values.service.http }}
    protocol: TCP
    name: app-{{ .Release.Name }}
  - name: smtp 
    port: {{ .Values.service.smtp }}
    targetPort: {{ .Values.service.smtp }}
    protocol: TCP
